name: .NET CI PIPELINE
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
    build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Source Code
         uses: actions/checkout@v4
       - name: Setup .NET 9
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 9.0.x 
       - name: Restore Dependencies
         run:  dotnet restore service/EmpManagemnt/EmpManagemnt.sln  
       - name: Build
         run:  dotnet build service/EmpManagemnt/EmpManagemnt.sln --configuration Release --no-restore 
       - name: Test
         run:  dotnet test service/EmpManagemnt/EmpManagemnt.sln --no-build --verbosity normal

